main: net.chevalier.staffutility.Main
name: StaffUtility
version: 1.0
author: Chevalier-Network
commands:
  staffutility:
    description: Show the plugin information.
  skick:
    description: Kick the player.
  sban:
    description: Ban the player.
  smute:
    description: Mute the player.
  swarn:
    description: Warn the player.
  force: